AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  CepApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev

  CepFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.12
      CodeUri: .
      Timeout: 10
      MemorySize: 128
      Events:
        CepApiEvent:
          Type: Api
          Properties:
            Path: /cep/{cep}
            Method: get
            RestApiId: !Ref CepApi
